### ISSUE TITLE
Todo: current list for per-pre-alpha of editor hacks

### ISSUE THREAD

**Issue by AurySystem** [AurySystem/bitsy-color#2]
- [x] rework rendering multiple colors
- <strike>add optional transparency for index zero/ alpha options to all indexes</strike> (do that later as well) instead of that do the next one
- [x] implement https://github.com/aloelazoe/bitsy-3d/tree/custom-drawing-size
- [x] fix all of #1 
- [x] make more bugs 
-  <strike>Add optional palette locking for drawings</strike>
- [x] change the color picker and palette interface
- [x] move brushcolor selection to reworked color picker
- [x] consider adding a rudimentary audio system. edited: considered to be too much to add for right now
-  add moving sprites, editing rooms, editing drawings, from dialogue (maybe, maybe not, not sure yet)
-  <strike>add icons to dialogue
-  add dialogue icon drawing type</strike> (moved to next version)
- [x] change recoloring index one to allow any hexadecimal color

- [x] rework life decisions

**Comment by Rathermaddy** [comment]
- [ ] consider a better way to use remappinging the first place

**Comment by AurySystem** [comment]
reworking
